from interfaceUtils import runCommand

from gdpc import Editor, Block, Transform, geometry
editor = Editor(buffering=True)






def buildPavilion(x, y, z, facing):
    for i in range(-5,6):
        for j in range(-5,6):
            editor.placeBlock((x+i,y,z+j),Block('smooth_quartz'))
    for i in range(-5,6):
        for j in range(-5,6):
            editor.placeBlock((x+i,y+1,z+j),Block('smooth_quartz'))
    for i in range(10):
        editor.placeBlock((x-4,y+2+i,z-4),Block('oak_log'))
        editor.placeBlock((x+4,y+2+i,z-4),Block('oak_log'))
        editor.placeBlock((x-4,y+2+i,z+4),Block('oak_log'))
        editor.placeBlock((x+4,y+2+i,z+4),Block('oak_log'))
    for i in range(-3,4):
        editor.placeBlock((x+i,y+11,z-4),Block('oak_log',{"axis": "x"}))
        editor.placeBlock((x+i,y+11,z+4),Block('oak_log',{"axis": "x"}))
        editor.placeBlock((x-4,y+11,z+i),Block('oak_log',{"axis": "z"}))
        editor.placeBlock((x+4,y+11,z+i),Block('oak_log',{"axis": "z"}))
    editor.placeBlock((x-5,y+11,z-4),Block('oak_log',{"axis": "x"}))
    editor.placeBlock((x+5,y+11,z-4),Block('oak_log',{"axis": "x"}))
    editor.placeBlock((x-5,y+11,z+4),Block('oak_log',{"axis": "x"}))
    editor.placeBlock((x+5,y+11,z+4),Block('oak_log',{"axis": "x"}))
    editor.placeBlock((x-4,y+11,z-5),Block('oak_log',{"axis": "z"}))
    editor.placeBlock((x-4,y+11,z+5),Block('oak_log',{"axis": "z"}))
    editor.placeBlock((x+4,y+11,z-5),Block('oak_log',{"axis": "z"}))
    editor.placeBlock((x+4,y+11,z+5),Block('oak_log',{"axis": "z"}))
    for i in range(-7,8):
        for j in range(-7,8):
            editor.placeBlock((x+i,y+12,z+j),Block('red_wool'))
    for i in range(-5,6):
        for j in range(-5,6):
            editor.placeBlock((x+i,y+13,z+j),Block('red_wool'))
    for i in range(-3,4):
        for j in range(-3,4):
            editor.placeBlock((x+i,y+14,z+j),Block('red_wool'))
    for i in range(-2,3):
        for j in range(-2,3):
            editor.placeBlock((x+i,y+15,z+j),Block('red_wool'))
    for i in range(-1,2):
        for j in range(-1,2):
            editor.placeBlock((x+i,y+16,z+j),Block('red_wool'))
    editor.placeBlock((x,y+17,z),Block('red_wool'))
    for i in range(-5,6,2):
        for j in range(2):
            editor.placeBlock((x+i,y+13,z+6+j),Block('red_wool'))
            editor.placeBlock((x+i,y+13,z-6-j),Block('red_wool'))
            editor.placeBlock((x+6+j,y+13,z+i),Block('red_wool'))
            editor.placeBlock((x-6-j,y+13,z+i),Block('red_wool'))
    for i in range(-3,4,2):
        for j in range(2):
            editor.placeBlock((x+i,y+14,z+4+j),Block('red_wool'))
            editor.placeBlock((x+i,y+14,z-4-j),Block('red_wool'))
            editor.placeBlock((x+4+j,y+14,z+i),Block('red_wool'))
            editor.placeBlock((x-4-j,y+14,z+i),Block('red_wool'))
    for i in [-1,1]:
        editor.placeBlock((x+i,y+15,z+3),Block('red_wool'))
        editor.placeBlock((x+i,y+15,z-3),Block('red_wool'))
        editor.placeBlock((x+3,y+15,z+i),Block('red_wool'))
        editor.placeBlock((x-3,y+15,z+i),Block('red_wool'))
        editor.placeBlock((x+i,y+16,z+2),Block('red_wool'))
        editor.placeBlock((x+i,y+16,z-2),Block('red_wool'))
        editor.placeBlock((x+2,y+16,z+i),Block('red_wool'))
        editor.placeBlock((x-2,y+16,z+i),Block('red_wool'))
    editor.placeBlock((x+7,y+13,z+7),Block('smooth_quartz'))
    editor.placeBlock((x+7,y+13,z-7),Block('smooth_quartz'))
    editor.placeBlock((x-7,y+13,z+7),Block('smooth_quartz'))
    editor.placeBlock((x-7,y+13,z-7),Block('smooth_quartz'))
    editor.placeBlock((x+7,y+14,z+7),Block('smooth_quartz'))
    editor.placeBlock((x+7,y+14,z-7),Block('smooth_quartz'))
    editor.placeBlock((x-7,y+14,z+7),Block('smooth_quartz'))
    editor.placeBlock((x-7,y+14,z-7),Block('smooth_quartz'))
    editor.placeBlock((x+6,y+13,z+6),Block('smooth_quartz'))
    editor.placeBlock((x+6,y+13,z-6),Block('smooth_quartz'))
    editor.placeBlock((x-6,y+13,z+6),Block('smooth_quartz'))
    editor.placeBlock((x-6,y+13,z-6),Block('smooth_quartz'))
    editor.placeBlock((x+6,y+14,z+6),Block('smooth_quartz'))
    editor.placeBlock((x+6,y+14,z-6),Block('smooth_quartz'))
    editor.placeBlock((x-6,y+14,z+6),Block('smooth_quartz'))
    editor.placeBlock((x-6,y+14,z-6),Block('smooth_quartz'))
    editor.placeBlock((x+5,y+14,z+5),Block('smooth_quartz'))
    editor.placeBlock((x+5,y+14,z-5),Block('smooth_quartz'))
    editor.placeBlock((x-5,y+14,z+5),Block('smooth_quartz'))
    editor.placeBlock((x-5,y+14,z-5),Block('smooth_quartz'))
    editor.placeBlock((x+4,y+14,z+4),Block('smooth_quartz'))
    editor.placeBlock((x+4,y+14,z-4),Block('smooth_quartz'))
    editor.placeBlock((x-4,y+14,z+4),Block('smooth_quartz'))
    editor.placeBlock((x-4,y+14,z-4),Block('smooth_quartz'))
    editor.placeBlock((x+4,y+15,z+4),Block('smooth_quartz'))
    editor.placeBlock((x+4,y+15,z-4),Block('smooth_quartz'))
    editor.placeBlock((x-4,y+15,z+4),Block('smooth_quartz'))
    editor.placeBlock((x-4,y+15,z-4),Block('smooth_quartz'))
    editor.placeBlock((x+3,y+15,z+3),Block('smooth_quartz'))
    editor.placeBlock((x+3,y+15,z-3),Block('smooth_quartz'))
    editor.placeBlock((x-3,y+15,z+3),Block('smooth_quartz'))
    editor.placeBlock((x-3,y+15,z-3),Block('smooth_quartz'))
    editor.placeBlock((x+3,y+16,z+3),Block('smooth_quartz'))
    editor.placeBlock((x+3,y+16,z-3),Block('smooth_quartz'))
    editor.placeBlock((x-3,y+16,z+3),Block('smooth_quartz'))
    editor.placeBlock((x-3,y+16,z-3),Block('smooth_quartz'))
    editor.placeBlock((x+2,y+16,z+2),Block('smooth_quartz'))
    editor.placeBlock((x+2,y+16,z-2),Block('smooth_quartz'))
    editor.placeBlock((x-2,y+16,z+2),Block('smooth_quartz'))
    editor.placeBlock((x-2,y+16,z-2),Block('smooth_quartz'))
    editor.placeBlock((x+2,y+17,z+2),Block('smooth_quartz'))
    editor.placeBlock((x+2,y+17,z-2),Block('smooth_quartz'))
    editor.placeBlock((x-2,y+17,z+2),Block('smooth_quartz'))
    editor.placeBlock((x-2,y+17,z-2),Block('smooth_quartz'))
    editor.placeBlock((x+1,y+17,z+1),Block('smooth_quartz'))
    editor.placeBlock((x+1,y+17,z-1),Block('smooth_quartz'))
    editor.placeBlock((x-1,y+17,z+1),Block('smooth_quartz'))
    editor.placeBlock((x-1,y+17,z-1),Block('smooth_quartz'))
    editor.placeBlock((x+1,y+18,z+1),Block('smooth_quartz'))
    editor.placeBlock((x+1,y+18,z-1),Block('smooth_quartz'))
    editor.placeBlock((x-1,y+18,z+1),Block('smooth_quartz'))
    editor.placeBlock((x-1,y+18,z-1),Block('smooth_quartz'))
    editor.placeBlock((x,y+18,z),Block('smooth_quartz'))
    editor.placeBlock((x,23,z),Block('glowstone'))
    editor.placeBlock((x+5,y+15,z+5),Block('smooth_quartz_slab'))
    editor.placeBlock((x+6,y+15,z+6),Block('smooth_quartz_slab'))
    editor.placeBlock((x-5,y+15,z-5),Block('smooth_quartz_slab'))
    editor.placeBlock((x-6,y+15,z-6),Block('smooth_quartz_slab'))
    editor.placeBlock((x-5,y+15,z+5),Block('smooth_quartz_slab'))
    editor.placeBlock((x-6,y+15,z+6),Block('smooth_quartz_slab'))
    editor.placeBlock((x+5,y+15,z-5),Block('smooth_quartz_slab'))
    editor.placeBlock((x+6,y+15,z-6),Block('smooth_quartz_slab'))
    editor.placeBlock((x+2,y+17,z+1),Block('smooth_quartz_stairs',{"facing": "west", "half": "top"}))
    editor.placeBlock((x+2,y+17,z-1),Block('smooth_quartz_stairs',{"facing": "west", "half": "top"}))
    editor.placeBlock((x-2,y+17,z+1),Block('smooth_quartz_stairs',{"facing": "east", "half": "top"}))
    editor.placeBlock((x-2,y+17,z-1),Block('smooth_quartz_stairs',{"facing": "east", "half": "top"}))
    editor.placeBlock((x+1,y+17,z+2),Block('smooth_quartz_stairs',{"facing": "north", "half": "top"}))
    editor.placeBlock((x-1,y+17,z+2),Block('smooth_quartz_stairs',{"facing": "north", "half": "top"}))
    editor.placeBlock((x+1,y+17,z-2),Block('smooth_quartz_stairs',{"facing": "south", "half": "top"}))
    editor.placeBlock((x-1,y+17,z-2),Block('smooth_quartz_stairs',{"facing": "south", "half": "top"}))
    editor.placeBlock((x+1,y+17,z),Block('smooth_quartz_stairs',{"facing": "west"}))
    editor.placeBlock((x-1,y+17,z),Block('smooth_quartz_stairs',{"facing": "east"}))
    editor.placeBlock((x,y+17,z+1),Block('smooth_quartz_stairs',{"facing": "north"}))
    editor.placeBlock((x,y+17,z-1),Block('smooth_quartz_stairs',{"facing": "south"}))
    editor.placeBlock((x+1,y+19,z+1),Block('cobblestone_wall'))
    editor.placeBlock((x-1,y+19,z-1),Block('cobblestone_wall'))
    editor.placeBlock((x-1,y+19,z+1),Block('cobblestone_wall'))
    editor.placeBlock((x+1,y+19,z-1),Block('cobblestone_wall'))
    editor.placeBlock((x+1,y+20,z+1),Block('smooth_quartz'))
    editor.placeBlock((x-1,y+20,z+1),Block('smooth_quartz'))
    editor.placeBlock((x+1,y+20,z-1),Block('smooth_quartz'))
    editor.placeBlock((x-1,y+20,z-1),Block('smooth_quartz'))
    editor.placeBlock((x+1,y+20,z),Block('smooth_quartz_stairs',{"facing": "west", "half": "top"}))
    editor.placeBlock((x-1,y+20,z),Block('smooth_quartz_stairs',{"facing": "east", "half": "top"}))
    editor.placeBlock((x,y+20,z+1),Block('smooth_quartz_stairs',{"facing": "north", "half": "top"}))
    editor.placeBlock((x,y+20,z-1),Block('smooth_quartz_stairs',{"facing": "south", "half": "top"}))
    editor.placeBlock((x+1,y+21,z),Block('smooth_quartz_slab'))
    editor.placeBlock((x-1,y+21,z),Block('smooth_quartz_slab'))
    editor.placeBlock((x,y+21,z+1),Block('smooth_quartz_slab'))
    editor.placeBlock((x,y+21,z-1),Block('smooth_quartz_slab'))
    editor.placeBlock((x,y+21,z),Block('smooth_quartz'))
    for i in range(3):
        editor.placeBlock((x,y+22+i,z),Block('cobblestone_wall'))
    for i in range(6):
        editor.placeBlock((x+8,y+12,z-5+2*i),Block('smooth_quartz_stairs',{"facing": "west", "half": "top"}))
        editor.placeBlock((x+8,y+13,z-5+2*i),Block('smooth_quartz_stairs',{"facing": "west"}))
        editor.placeBlock((x-8,y+12,z-5+2*i),Block('smooth_quartz_stairs',{"facing": "east", "half": "top"}))
        editor.placeBlock((x-8,y+13,z-5+2*i),Block('smooth_quartz_stairs',{"facing": "east"}))
        editor.placeBlock((x-5+2*i,y+12,z+8),Block('smooth_quartz_stairs',{"facing": "north", "half": "top"}))
        editor.placeBlock((x-5+2*i,y+13,z+8),Block('smooth_quartz_stairs',{"facing": "north"}))
        editor.placeBlock((x-5+2*i,y+12,z-8),Block('smooth_quartz_stairs',{"facing": "south", "half": "top"}))
        editor.placeBlock((x-5+2*i,y+13,z-8),Block('smooth_quartz_stairs',{"facing": "south"}))
    for i in range(7):
        editor.placeBlock((x+8,y+12,z-6+2*i),Block('smooth_quartz_slab',{"type": "top"}))
        editor.placeBlock((x-8,y+12,z-6+2*i),Block('smooth_quartz_slab',{"type": "top"}))
        editor.placeBlock((x-6+2*i,y+12,z+8),Block('smooth_quartz_slab',{"type": "top"}))
        editor.placeBlock((x-6+2*i,y+12,z-8),Block('smooth_quartz_slab',{"type": "top"}))
    editor.placeBlock((x+8,y+12,z+7),Block('smooth_quartz_slab',{"type": "top"}))
    editor.placeBlock((x+8,y+12,z-7),Block('smooth_quartz_slab',{"type": "top"}))
    editor.placeBlock((x-8,y+12,z+7),Block('smooth_quartz_slab',{"type": "top"}))
    editor.placeBlock((x-8,y+12,z-7),Block('smooth_quartz_slab',{"type": "top"}))
    editor.placeBlock((x+7,y+12,z+8),Block('smooth_quartz_slab',{"type": "top"}))
    editor.placeBlock((x-7,y+12,z+8),Block('smooth_quartz_slab',{"type": "top"}))
    editor.placeBlock((x+7,y+12,z-8),Block('smooth_quartz_slab',{"type": "top"}))
    editor.placeBlock((x-7,y+12,z-8),Block('smooth_quartz_slab',{"type": "top"}))
    editor.placeBlock((x+7,y+13,z+6),Block('smooth_quartz_slab'))
    editor.placeBlock((x+7,y+13,z-6),Block('smooth_quartz_slab'))
    editor.placeBlock((x-7,y+13,z+6),Block('smooth_quartz_slab'))
    editor.placeBlock((x-7,y+13,z-6),Block('smooth_quartz_slab'))
    editor.placeBlock((x+6,y+13,z+7),Block('smooth_quartz_slab'))
    editor.placeBlock((x-6,y+13,z+7),Block('smooth_quartz_slab'))
    editor.placeBlock((x+6,y+13,z-7),Block('smooth_quartz_slab'))
    editor.placeBlock((x-6,y+13,z-7),Block('smooth_quartz_slab'))
    editor.placeBlock((x+8,y+13,z+6),Block('smooth_quartz_slab'))
    editor.placeBlock((x+8,y+13,z-6),Block('smooth_quartz_slab'))
    editor.placeBlock((x-8,y+13,z+6),Block('smooth_quartz_slab'))
    editor.placeBlock((x-8,y+13,z-6),Block('smooth_quartz_slab'))
    editor.placeBlock((x+6,y+13,z+8),Block('smooth_quartz_slab'))
    editor.placeBlock((x-6,y+13,z+8),Block('smooth_quartz_slab'))
    editor.placeBlock((x+6,y+13,z-8),Block('smooth_quartz_slab'))
    editor.placeBlock((x-6,y+13,z-8),Block('smooth_quartz_slab'))
    editor.placeBlock((x+8,y+13,z+7),Block('smooth_quartz'))
    editor.placeBlock((x+8,y+13,z-7),Block('smooth_quartz'))
    editor.placeBlock((x-8,y+13,z+7),Block('smooth_quartz'))
    editor.placeBlock((x-8,y+13,z-7),Block('smooth_quartz'))
    editor.placeBlock((x+7,y+13,z+8),Block('smooth_quartz'))
    editor.placeBlock((x-7,y+13,z+8),Block('smooth_quartz'))
    editor.placeBlock((x+7,y+13,z-8),Block('smooth_quartz'))
    editor.placeBlock((x-7,y+13,z-8),Block('smooth_quartz'))
    editor.placeBlock((x+8,y+13,z+8),Block('smooth_quartz'))
    editor.placeBlock((x+8,y+13,z-8),Block('smooth_quartz'))
    editor.placeBlock((x-8,y+13,z+8),Block('smooth_quartz'))
    editor.placeBlock((x-8,y+13,z-8),Block('smooth_quartz'))
    editor.placeBlock((x+8,y+14,z+8),Block('smooth_quartz'))
    editor.placeBlock((x+8,y+14,z-8),Block('smooth_quartz'))
    editor.placeBlock((x-8,y+14,z+8),Block('smooth_quartz'))
    editor.placeBlock((x-8,y+14,z-8),Block('smooth_quartz'))
    for i in range(3):
        editor.placeBlock((x+5,y+11-i,z+5),Block('oak_log'))
        editor.placeBlock((x+5,y+11-i,z-5),Block('oak_log'))
        editor.placeBlock((x-5,y+11-i,z+5),Block('oak_log'))
        editor.placeBlock((x-5,y+11-i,z-5),Block('oak_log'))
    for i in range(5):
        editor.placeBlock((x+5,y+i,z+5),Block('oak_log'))
        editor.placeBlock((x+5,y+i,z-5),Block('oak_log'))
        editor.placeBlock((x-5,y+i,z+5),Block('oak_log'))
        editor.placeBlock((x-5,y+i,z-5),Block('oak_log'))
    for i in range(4):
        editor.placeBlock((x+5,y+5+i,z+5),Block('cobblestone_wall'))
        editor.placeBlock((x+5,y+5+i,z-5),Block('cobblestone_wall'))
        editor.placeBlock((x-5,y+5+i,z+5),Block('cobblestone_wall'))
        editor.placeBlock((x-5,y+5+i,z-5),Block('cobblestone_wall'))
    editor.placeBlock((x+6,y+11,z+6),Block('oak_log'))
    editor.placeBlock((x+6,y+11,z-6),Block('oak_log'))
    editor.placeBlock((x-6,y+11,z+6),Block('oak_log'))
    editor.placeBlock((x-6,y+11,z-6),Block('oak_log'))
    editor.placeBlock((x+7,y+12,z+7),Block('oak_log'))
    editor.placeBlock((x+7,y+12,z-7),Block('oak_log'))
    editor.placeBlock((x-7,y+12,z+7),Block('oak_log'))
    editor.placeBlock((x-7,y+12,z-7),Block('oak_log'))
    for i in range(6):
        if i == 0 or i == 5:
            for j in range(2):
                editor.placeBlock((x+6+j,y+11,z-5+2*i),Block('smooth_quartz_slab',{"type": "top"}))
                editor.placeBlock((x-6-j,y+11,z-5+2*i),Block('smooth_quartz_slab',{"type": "top"}))
                editor.placeBlock((x-5+2*i,y+11,z+6+j),Block('smooth_quartz_slab',{"type": "top"}))
                editor.placeBlock((x-5+2*i,y+11,z-6-j),Block('smooth_quartz_slab',{"type": "top"}))
        else:
            for j in range(3):
                editor.placeBlock((x+5+j,y+11,z-5+2*i),Block('smooth_quartz_slab',{"type": "top"}))
                editor.placeBlock((x-5-j,y+11,z-5+2*i),Block('smooth_quartz_slab',{"type": "top"}))
                editor.placeBlock((x-5+2*i,y+11,z+5+j),Block('smooth_quartz_slab',{"type": "top"}))
                editor.placeBlock((x-5+2*i,y+11,z-5-j),Block('smooth_quartz_slab',{"type": "top"}))
    editor.placeBlock((x+6,y+10,z+6),Block('smooth_quartz_slab',{"type": "top"}))
    editor.placeBlock((x+6,y+10,z-6),Block('smooth_quartz_slab',{"type": "top"}))
    editor.placeBlock((x-6,y+10,z+6),Block('smooth_quartz_slab',{"type": "top"}))
    editor.placeBlock((x-6,y+10,z-6),Block('smooth_quartz_slab',{"type": "top"}))
    editor.placeBlock((x+7,y+11,z+7),Block('smooth_quartz_slab',{"type": "top"}))
    editor.placeBlock((x+7,y+11,z-7),Block('smooth_quartz_slab',{"type": "top"}))
    editor.placeBlock((x-7,y+11,z+7),Block('smooth_quartz_slab',{"type": "top"}))
    editor.placeBlock((x-7,y+11,z-7),Block('smooth_quartz_slab',{"type": "top"}))
    for i in range(3):
        editor.placeBlock((x+5,y+11,z-2+2*i),Block('smooth_quartz_slab',{"type": "top"}))
        editor.placeBlock((x-5,y+11,z-2+2*i),Block('smooth_quartz_slab',{"type": "top"}))
        editor.placeBlock((x-2+2*i,y+11,z+5),Block('smooth_quartz_slab',{"type": "top"}))
        editor.placeBlock((x-2+2*i,y+11,z-5),Block('smooth_quartz_slab',{"type": "top"}))
    editor.placeBlock((x+5,y+11,z+4),Block('smooth_quartz_stairs',{"facing": "west", "half": "top"}))
    editor.placeBlock((x+5,y+11,z-4),Block('smooth_quartz_stairs',{"facing": "west", "half": "top"}))
    editor.placeBlock((x-5,y+11,z+4),Block('smooth_quartz_stairs',{"facing": "east", "half": "top"}))
    editor.placeBlock((x-5,y+11,z-4),Block('smooth_quartz_stairs',{"facing": "east", "half": "top"}))
    editor.placeBlock((x+4,y+11,z+5),Block('smooth_quartz_stairs',{"facing": "north", "half": "top"}))
    editor.placeBlock((x-4,y+11,z+5),Block('smooth_quartz_stairs',{"facing": "north", "half": "top"}))
    editor.placeBlock((x+4,y+11,z-5),Block('smooth_quartz_stairs',{"facing": "south", "half": "top"}))
    editor.placeBlock((x-4,y+11,z-5),Block('smooth_quartz_stairs',{"facing": "south", "half": "top"}))
    for i in range(-3,4):
        editor.placeBlock((x+4,y+9,z+i),Block('smooth_quartz_slab',{"type": "top"}))
        editor.placeBlock((x-4,y+9,z+i),Block('smooth_quartz_slab',{"type": "top"}))
        editor.placeBlock((x+i,y+9,z+4),Block('smooth_quartz_slab',{"type": "top"}))
        editor.placeBlock((x+i,y+9,z-4),Block('smooth_quartz_slab',{"type": "top"}))
        editor.placeBlock((x+4,y+10,z+i),Block('smooth_quartz_slab',{"type": "top"}))
        editor.placeBlock((x-4,y+10,z+i),Block('smooth_quartz_slab',{"type": "top"}))
        editor.placeBlock((x+i,y+10,z+4),Block('smooth_quartz_slab',{"type": "top"}))
        editor.placeBlock((x+i,y+10,z-4),Block('smooth_quartz_slab',{"type": "top"}))
    editor.placeBlock((x+4,y+9,z+3),Block('smooth_quartz_stairs',{"facing": "south", "half": "top"}))
    editor.placeBlock((x-4,y+9,z+3),Block('smooth_quartz_stairs',{"facing": "south", "half": "top"}))
    editor.placeBlock((x+4,y+9,z-3),Block('smooth_quartz_stairs',{"facing": "north", "half": "top"}))
    editor.placeBlock((x-4,y+9,z-3),Block('smooth_quartz_stairs',{"facing": "north", "half": "top"}))
    editor.placeBlock((x+3,y+9,z+4),Block('smooth_quartz_stairs',{"facing": "east", "half": "top"}))
    editor.placeBlock((x+3,y+9,z-4),Block('smooth_quartz_stairs',{"facing": "east", "half": "top"}))
    editor.placeBlock((x-3,y+9,z+4),Block('smooth_quartz_stairs',{"facing": "west", "half": "top"}))
    editor.placeBlock((x-3,y+9,z-4),Block('smooth_quartz_stairs',{"facing": "west", "half": "top"}))
    editor.placeBlock((x+4,y+10,z+2),Block('smooth_quartz_stairs',{"facing": "north", "half": "top"}))
    editor.placeBlock((x-4,y+10,z+2),Block('smooth_quartz_stairs',{"facing": "north", "half": "top"}))
    editor.placeBlock((x+4,y+10,z-2),Block('smooth_quartz_stairs',{"facing": "south", "half": "top"}))
    editor.placeBlock((x-4,y+10,z-2),Block('smooth_quartz_stairs',{"facing": "south", "half": "top"}))
    editor.placeBlock((x+2,y+10,z+4),Block('smooth_quartz_stairs',{"facing": "west", "half": "top"}))
    editor.placeBlock((x+2,y+10,z-4),Block('smooth_quartz_stairs',{"facing": "west", "half": "top"}))
    editor.placeBlock((x-2,y+10,z+4),Block('smooth_quartz_stairs',{"facing": "east", "half": "top"}))
    editor.placeBlock((x-2,y+10,z-4),Block('smooth_quartz_stairs',{"facing": "east", "half": "top"}))
    for i,j in [(4,4),(4,-4),(-4,4),(-4,-4)]:
        editor.placeBlock((x+i+1,y+4,z+j),Block('smooth_quartz_stairs',{"facing": "west"}))
        editor.placeBlock((x+i-1,y+4,z+j),Block('smooth_quartz_stairs',{"facing": "east"}))
        editor.placeBlock((x+i,y+4,z+j+1),Block('smooth_quartz_stairs',{"facing": "north"}))
        editor.placeBlock((x+i,y+4,z+j-1),Block('smooth_quartz_stairs',{"facing": "south"}))
        editor.placeBlock((x+i+1,y+3,z+j),Block('cobblestone_wall'))
        editor.placeBlock((x+i-1,y+3,z+j),Block('cobblestone_wall'))
        editor.placeBlock((x+i,y+3,z+j+1),Block('cobblestone_wall'))
        editor.placeBlock((x+i,y+3,z+j-1),Block('cobblestone_wall'))
        editor.placeBlock((x+i+1,y+2,z+j),Block('smooth_quartz_stairs',{"facing": "west", "half": "top"}))
        editor.placeBlock((x+i-1,y+2,z+j),Block('smooth_quartz_stairs',{"facing": "east", "half": "top"}))
        editor.placeBlock((x+i,y+2,z+j+1),Block('smooth_quartz_stairs',{"facing": "north", "half": "top"}))
        editor.placeBlock((x+i,y+2,z+j-1),Block('smooth_quartz_stairs',{"facing": "south", "half": "top"}))
    if facing != 'w':
        for i in range(-2,3):
            editor.placeBlock((x+5,y+2,z+i),Block('smooth_quartz_slab',{"type": "top"}))
        editor.placeBlock((x+5,y+2,z-3),Block('smooth_quartz_stairs',{"facing": "west"}))
        editor.placeBlock((x+5,y+2,z+3),Block('smooth_quartz_stairs',{"facing": "west"}))
    if facing != 'e':
        for i in range(-2,3):
            editor.placeBlock((x-5,y+2,z+i),Block('smooth_quartz_slab',{"type": "top"}))
        editor.placeBlock((x-5,y+2,z-3),Block('smooth_quartz_stairs',{"facing": "east"}))
        editor.placeBlock((x-5,y+2,z+3),Block('smooth_quartz_stairs',{"facing": "east"}))
    if facing != 'n':
        for i in range(-2,3):
            editor.placeBlock((x+i,y+2,z+5),Block('smooth_quartz_slab',{"type": "top"}))
        editor.placeBlock((x-3,y+2,z+5),Block('smooth_quartz_stairs',{"facing": "north"}))
        editor.placeBlock((x+3,y+2,z+5),Block('smooth_quartz_stairs',{"facing": "north"}))
    if facing != 's':
        for i in range(-2,3):
            editor.placeBlock((x-i,y+2,z-5),Block('smooth_quartz_slab',{"type": "top"}))
        editor.placeBlock((x-3,y+2,z-5),Block('smooth_quartz_stairs',{"facing": "south"}))
        editor.placeBlock((x+3,y+2,z-5),Block('smooth_quartz_stairs',{"facing": "south"}))
    if facing == 'w':
        for i in range(-3,4):
            editor.placeBlock((x+6,y,z+i),Block('smooth_quartz'))
            editor.placeBlock((x+6,y+1,z+i),Block('smooth_quartz_slab'))
            editor.placeBlock((x+7,y,z+i),Block('smooth_quartz'))
            editor.placeBlock((x+8,y,z+i),Block('smooth_quartz_slab'))
        editor.placeBlock((x+6,y+1,z+3),Block('smooth_quartz'))
        editor.placeBlock((x+6,y+1,z-3),Block('smooth_quartz'))
        editor.placeBlock((x+7,y+1,z+3),Block('smooth_quartz_slab'))
        editor.placeBlock((x+7,y+1,z-3),Block('smooth_quartz_slab'))
        editor.placeBlock((x+8,y,z+3),Block('smooth_quartz'))
        editor.placeBlock((x+8,y,z-3),Block('smooth_quartz'))
        editor.placeBlock((x+9,y,z+3),Block('smooth_quartz_slab'))
        editor.placeBlock((x+9,y,z-3),Block('smooth_quartz_slab'))
    elif facing == 'e':
        for i in range(-3,4):
            editor.placeBlock((x-6,y,z+i),Block('smooth_quartz'))
            editor.placeBlock((x-6,y+1,z+i),Block('smooth_quartz_slab'))
            editor.placeBlock((x-7,y,z+i),Block('smooth_quartz'))
            editor.placeBlock((x-8,y,z+i),Block('smooth_quartz_slab'))
        editor.placeBlock((x-6,y+1,z+3),Block('smooth_quartz'))
        editor.placeBlock((x-6,y+1,z-3),Block('smooth_quartz'))
        editor.placeBlock((x-7,y+1,z+3),Block('smooth_quartz_slab'))
        editor.placeBlock((x-7,y+1,z-3),Block('smooth_quartz_slab'))
        editor.placeBlock((x-8,y,z+3),Block('smooth_quartz'))
        editor.placeBlock((x-8,y,z-3),Block('smooth_quartz'))
        editor.placeBlock((x-9,y,z+3),Block('smooth_quartz_slab'))
        editor.placeBlock((x-9,y,z-3),Block('smooth_quartz_slab'))
    elif facing == 'n':
        for i in range(-3,4):
            editor.placeBlock((x+i,y,z+6),Block('smooth_quartz'))
            editor.placeBlock((x+i,y+1,z+6),Block('smooth_quartz_slab'))
            editor.placeBlock((x+i,y,z+7),Block('smooth_quartz'))
            editor.placeBlock((x+i,y,z+8),Block('smooth_quartz_slab'))
        editor.placeBlock((x+3,y+1,z+6),Block('smooth_quartz'))
        editor.placeBlock((x-3,y+1,z+6),Block('smooth_quartz'))
        editor.placeBlock((x+3,y+1,z+7),Block('smooth_quartz_slab'))
        editor.placeBlock((x-3,y+1,z+7),Block('smooth_quartz_slab'))
        editor.placeBlock((x+3,y,z+8),Block('smooth_quartz'))
        editor.placeBlock((x-3,y,z+8),Block('smooth_quartz'))
        editor.placeBlock((x+3,y,z+9),Block('smooth_quartz_slab'))
        editor.placeBlock((x-3,y,z+9),Block('smooth_quartz_slab'))
    elif facing == 's':
        for i in range(-3,4):
            editor.placeBlock((x+i,y,z-6),Block('smooth_quartz'))
            editor.placeBlock((x+i,y+1,z-6),Block('smooth_quartz_slab'))
            editor.placeBlock((x+i,y,z-7),Block('smooth_quartz'))
            editor.placeBlock((x+i,y,z-8),Block('smooth_quartz_slab'))
        editor.placeBlock((x+3,y+1,z-6),Block('smooth_quartz'))
        editor.placeBlock((x-3,y+1,z-6),Block('smooth_quartz'))
        editor.placeBlock((x+3,y+1,z-7),Block('smooth_quartz_slab'))
        editor.placeBlock((x-3,y+1,z-7),Block('smooth_quartz_slab'))
        editor.placeBlock((x+3,y,z-8),Block('smooth_quartz'))
        editor.placeBlock((x-3,y,z-8),Block('smooth_quartz'))
        editor.placeBlock((x+3,y,z-9),Block('smooth_quartz_slab'))
        editor.placeBlock((x-3,y,z-9),Block('smooth_quartz_slab'))
    #light
    editor.placeBlock((x,y+1,z),Block("shroomlight"))
    editor.placeBlock((x-4,y+3,z-4),Block("shroomlight"))
    editor.placeBlock((x-4,y+3,z+4),Block("shroomlight"))
    editor.placeBlock((x+4,y+3,z-4),Block("shroomlight"))
    editor.placeBlock((x+4,y+3,z+4),Block("shroomlight"))
    editor.placeBlock((x-8,y+13,z),Block("lantern"))
    editor.placeBlock((x+8,y+13,z),Block("lantern"))
    editor.placeBlock((x,y+13,z-8),Block("lantern"))
    editor.placeBlock((x,y+13,z+8),Block("lantern"))
    editor.placeBlock((x+3,y+17,z+3),Block("lantern"))
    editor.placeBlock((x+3,y+17,z-3),Block("lantern"))
    editor.placeBlock((x-3,y+17,z+3),Block("lantern"))
    editor.placeBlock((x-3,y+17,z-3),Block("lantern"))
    editor.placeBlock((x+7,y+15,z+7),Block("lantern"))
    editor.placeBlock((x+7,y+15,z-7),Block("lantern"))
    editor.placeBlock((x-7,y+15,z+7),Block("lantern"))
    editor.placeBlock((x-7,y+15,z-7),Block("lantern"))

def rectanglesOverlap(r1, r2):
    """Check that r1 and r2 do not overlap."""
    if (r1 >= r2 + r2[2]) or (r1 + r1[2] <= r2) or (r1 + r1 <= r2) or (r1 >= r2 + r2):
        return False
    else:
        return True