from interfaceUtils import runCommand

import random
from interfaceUtils import runCommand
from gdpc import Editor, Block, Transform, geometry
editor = Editor(buffering=True)




def check_coor(x,y,z):
    command = f"summon minecraft:shulker {x} {y} {z} {{Invulnerable:true,Glowing:true,Silent:true,Tags:[test],NoAI:true,PersistenceRequired:true}}"
    print("座標確認用ブロックを生成")
    runCommand(command)




def buildTowerBottom(x, y, z):
    for i in range(-4,5):
        for j in range(-4,5):
            for m in range(2):
                editor.placeBlock((x+i,y+m,z+j),Block('cobblestone'))
    for i in range(-1,2):
        for m in range(2):
            editor.placeBlock((x+5,y+m,z+i),Block('cobblestone'))
            editor.placeBlock((x-5,y+m,z+i),Block('cobblestone'))
            editor.placeBlock((x+i,y+m,z+5),Block('cobblestone'))
            editor.placeBlock((x+i,y+m,z-5),Block('cobblestone'))
        editor.placeBlock((x+6,y,z+i),Block('cobblestone'))
        editor.placeBlock((x-6,y,z+i),Block('cobblestone'))
        editor.placeBlock((x+i,y,z+6),Block('cobblestone'))
        editor.placeBlock((x+i,y,z-6),Block('cobblestone'))
        editor.placeBlock((x+6,y+1,z+i),Block('stone_bricks'))
        editor.placeBlock((x-6,y+1,z+i),Block('stone_bricks'))
        editor.placeBlock((x+i,y+1,z+6),Block('stone_bricks'))
        editor.placeBlock((x+i,y+1,z-6),Block('stone_bricks'))
        editor.placeBlock((x+7,y,z+i),Block('stone_bricks'))
        editor.placeBlock((x-7,y,z+i),Block('stone_bricks'))
        editor.placeBlock((x+i,y,z+7),Block('stone_bricks'))
        editor.placeBlock((x+i,y,z-7),Block('stone_bricks'))
    editor.placeBlock((x+6,y+1,z),Block('stone_brick_slab'))
    editor.placeBlock((x-6,y+1,z),Block('stone_brick_slab'))
    editor.placeBlock((x,y+1,z+6),Block('stone_brick_slab'))
    editor.placeBlock((x,y+1,z-6),Block('stone_brick_slab'))
    editor.placeBlock((x+7,y,z),Block('stone_brick_slab'))
    editor.placeBlock((x-7,y,z),Block('stone_brick_slab'))
    editor.placeBlock((x,y,z+7),Block('stone_brick_slab'))
    editor.placeBlock((x,y,z-7),Block('stone_brick_slab'))
    editor.placeBlock((x+5,y,z+2),Block('stone_brick_stairs',{"facing": "north"}))
    editor.placeBlock((x+5,y,z-2),Block('stone_brick_stairs',{"facing": "south"}))
    editor.placeBlock((x+5,y+1,z+2),Block('stone_brick_stairs',{"facing": "north", "half": "top"}))
    editor.placeBlock((x+5,y+1,z-2),Block('stone_brick_stairs',{"facing": "south", "half": "top"}))
    editor.placeBlock((x-5,y,z+2),Block('stone_brick_stairs',{"facing": "north"}))
    editor.placeBlock((x-5,y,z-2),Block('stone_brick_stairs',{"facing": "south"}))
    editor.placeBlock((x-5,y+1,z+2),Block('stone_brick_stairs',{"facing": "north", "half": "top"}))
    editor.placeBlock((x-5,y+1,z-2),Block('stone_brick_stairs',{"facing": "south", "half": "top"}))
    editor.placeBlock((x+2,y,z+5),Block('stone_brick_stairs',{"facing": "west"}))
    editor.placeBlock((x-2,y,z+5),Block('stone_brick_stairs',{"facing": "east"}))
    editor.placeBlock((x+2,y+1,z+5),Block('stone_brick_stairs',{"facing": "west", "half": "top"}))
    editor.placeBlock((x-2,y+1,z+5),Block('stone_brick_stairs',{"facing": "east", "half": "top"}))
    editor.placeBlock((x+2,y,z-5),Block('stone_brick_stairs',{"facing": "west"}))
    editor.placeBlock((x-2,y,z-5),Block('stone_brick_stairs',{"facing": "east"}))
    editor.placeBlock((x+2,y+1,z-5),Block('stone_brick_stairs',{"facing": "west", "half": "top"}))
    editor.placeBlock((x-2,y+1,z-5),Block('stone_brick_stairs',{"facing": "east", "half": "top"}))
    for i in [-4,-3,3,4]:
        editor.placeBlock((x+5,y,z+i),Block('stone_brick_slab'))
        editor.placeBlock((x-5,y,z+i),Block('stone_brick_slab'))
        editor.placeBlock((x+i,y,z+5),Block('stone_brick_slab'))
        editor.placeBlock((x+i,y,z-5),Block('stone_brick_slab'))
        editor.placeBlock((x+5,y+1,z+i),Block('stone_brick_slab',{"type": "top"}))
        editor.placeBlock((x-5,y+1,z+i),Block('stone_brick_slab',{"type": "top"}))
        editor.placeBlock((x+i,y+1,z+5),Block('stone_brick_slab',{"type": "top"}))
        editor.placeBlock((x+i,y+1,z-5),Block('stone_brick_slab',{"type": "top"}))
    editor.placeBlock((x+5,y,z+5),Block('stone_bricks'))
    editor.placeBlock((x+5,y,z-5),Block('stone_bricks'))
    editor.placeBlock((x-5,y,z+5),Block('stone_bricks'))
    editor.placeBlock((x-5,y,z-5),Block('stone_bricks'))
    editor.placeBlock((x+5,y+1,z+5),Block('stone_bricks'))
    editor.placeBlock((x+5,y+1,z-5),Block('stone_bricks'))
    editor.placeBlock((x-5,y+1,z+5),Block('stone_bricks'))
    editor.placeBlock((x-5,y+1,z-5),Block('stone_bricks'))
    editor.placeBlock((x+6,y,z+2),Block('stone_brick_stairs',{"facing": "north", "half": "top"}))
    editor.placeBlock((x+6,y,z-2),Block('stone_brick_stairs',{"facing": "south", "half": "top"}))
    editor.placeBlock((x+6,y+1,z+2),Block('stone_brick_stairs',{"facing": "south"}))
    editor.placeBlock((x+6,y+1,z-2),Block('stone_brick_stairs',{"facing": "north"}))
    editor.placeBlock((x-6,y,z+2),Block('stone_brick_stairs',{"facing": "north", "half": "top"}))
    editor.placeBlock((x-6,y,z-2),Block('stone_brick_stairs',{"facing": "south", "half": "top"}))
    editor.placeBlock((x-6,y+1,z+2),Block('stone_brick_stairs',{"facing": "south"}))
    editor.placeBlock((x-6,y+1,z-2),Block('stone_brick_stairs',{"facing": "north"}))
    editor.placeBlock((x+2,y,z+6),Block('stone_brick_stairs',{"facing": "west", "half": "top"}))
    editor.placeBlock((x-2,y,z+6),Block('stone_brick_stairs',{"facing": "east", "half": "top"}))
    editor.placeBlock((x+2,y+1,z+6),Block('stone_brick_stairs',{"facing": "east"}))
    editor.placeBlock((x-2,y+1,z+6),Block('stone_brick_stairs',{"facing": "west"}))
    editor.placeBlock((x+2,y,z-6),Block('stone_brick_stairs',{"facing": "west", "half": "top"}))
    editor.placeBlock((x-2,y,z-6),Block('stone_brick_stairs',{"facing": "east", "half": "top"}))
    editor.placeBlock((x+2,y+1,z-6),Block('stone_brick_stairs',{"facing": "east"}))
    editor.placeBlock((x-2,y+1,z-6),Block('stone_brick_stairs',{"facing": "west"}))
    editor.placeBlock((x+5,y,z+6),Block('stone_brick_stairs',{"facing": "north", "half": "top"}))
    editor.placeBlock((x+5,y+1,z+6),Block('stone_brick_stairs',{"facing": "south"}))
    editor.placeBlock((x-5,y,z+6),Block('stone_brick_stairs',{"facing": "north", "half": "top"}))
    editor.placeBlock((x-5,y+1,z+6),Block('stone_brick_stairs',{"facing": "south"}))
    editor.placeBlock((x+5,y,z-6),Block('stone_brick_stairs',{"facing": "south", "half": "top"}))
    editor.placeBlock((x+5,y+1,z-6),Block('stone_brick_stairs',{"facing": "north"}))
    editor.placeBlock((x-5,y,z-6),Block('stone_brick_stairs',{"facing": "south", "half": "top"}))
    editor.placeBlock((x-5,y+1,z-6),Block('stone_brick_stairs',{"facing": "north"}))
    editor.placeBlock((x+6,y,z+5),Block('stone_brick_stairs',{"facing": "west", "half": "top"}))
    editor.placeBlock((x+6,y+1,z+5),Block('stone_brick_stairs',{"facing": "east"}))
    editor.placeBlock((x+6,y,z-5),Block('stone_brick_stairs',{"facing": "west", "half": "top"}))
    editor.placeBlock((x+6,y+1,z-5),Block('stone_brick_stairs',{"facing": "east"}))
    editor.placeBlock((x-6,y,z+5),Block('stone_brick_stairs',{"facing": "east", "half": "top"}))
    editor.placeBlock((x-6,y+1,z+5),Block('stone_brick_stairs',{"facing": "west"}))
    editor.placeBlock((x-6,y,z-5),Block('stone_brick_stairs',{"facing": "east", "half": "top"}))
    editor.placeBlock((x-6,y+1,z-5),Block('stone_brick_stairs',{"facing": "west"}))
    for i in [-4,-2,2,4]:
        editor.placeBlock((x+4,y+2,z+i),Block('smooth_stone_slab',{"type": "double"}))
        editor.placeBlock((x-4,y+2,z+i),Block('smooth_stone_slab',{"type": "double"}))
        editor.placeBlock((x+i,y+2,z+4),Block('smooth_stone_slab',{"type": "double"}))
        editor.placeBlock((x+i,y+2,z-4),Block('smooth_stone_slab',{"type": "double"}))
    editor.placeBlock((x+4,y+2,z+3),Block('smooth_stone_slab',{"type": "top"}))
    editor.placeBlock((x+4,y+2,z-3),Block('smooth_stone_slab',{"type": "top"}))
    editor.placeBlock((x-4,y+2,z+3),Block('smooth_stone_slab',{"type": "top"}))
    editor.placeBlock((x-4,y+2,z-3),Block('smooth_stone_slab',{"type": "top"}))
    editor.placeBlock((x+3,y+2,z+4),Block('smooth_stone_slab',{"type": "top"}))
    editor.placeBlock((x-3,y+2,z+4),Block('smooth_stone_slab',{"type": "top"}))
    editor.placeBlock((x+3,y+2,z-4),Block('smooth_stone_slab',{"type": "top"}))
    editor.placeBlock((x-3,y+2,z-4),Block('smooth_stone_slab',{"type": "top"}))
    editor.placeBlock((x+4,y+2,z+1),Block('smooth_stone_slab'))
    editor.placeBlock((x+4,y+2,z-1),Block('smooth_stone_slab'))
    editor.placeBlock((x-4,y+2,z+1),Block('smooth_stone_slab'))
    editor.placeBlock((x-4,y+2,z-1),Block('smooth_stone_slab'))
    editor.placeBlock((x+1,y+2,z+4),Block('smooth_stone_slab'))
    editor.placeBlock((x-1,y+2,z+4),Block('smooth_stone_slab'))
    editor.placeBlock((x+1,y+2,z-4),Block('smooth_stone_slab'))
    editor.placeBlock((x-1,y+2,z-4),Block('smooth_stone_slab'))
    for i in [-4,-2,2,4]:
        editor.placeBlock((x+4,y+3,z+i),Block('smooth_stone_slab'))
        editor.placeBlock((x-4,y+3,z+i),Block('smooth_stone_slab'))
        editor.placeBlock((x+i,y+3,z+4),Block('smooth_stone_slab'))
        editor.placeBlock((x+i,y+3,z-4),Block('smooth_stone_slab'))
        editor.placeBlock((x+4,y+2,z+1),Block('smooth_stone_slab'))
    editor.placeBlock((x+5,y+1,z+1),Block('stone_bricks'))
    editor.placeBlock((x+5,y+1,z-1),Block('stone_bricks'))
    editor.placeBlock((x-5,y+1,z+1),Block('stone_bricks'))
    editor.placeBlock((x-5,y+1,z-1),Block('stone_bricks'))
    editor.placeBlock((x+1,y+1,z+5),Block('stone_bricks'))
    editor.placeBlock((x-1,y+1,z+5),Block('stone_bricks'))
    editor.placeBlock((x+1,y+1,z-5),Block('stone_bricks'))
    editor.placeBlock((x-1,y+1,z-5),Block('stone_bricks'))
    editor.placeBlock((x,y+1,z),Block("shroomlight"))
    editor.placeBlock((x-3,y+1,z-4),Block("shroomlight"))
    editor.placeBlock((x+3,y+1,z-4),Block("shroomlight"))
    editor.placeBlock((x-3,y+1,z+4),Block("shroomlight"))
    editor.placeBlock((x+3,y+1,z+4),Block("shroomlight"))
    editor.placeBlock((x+4,y+1,z+3),Block("shroomlight"))
    editor.placeBlock((x+4,y+1,z-3),Block("shroomlight"))
    editor.placeBlock((x-4,y+1,z+3),Block("shroomlight"))
    editor.placeBlock((x-4,y+1,z-3),Block("shroomlight"))

def buildTowerFloor(x, y, z, flag):
    for i in range(7):
        editor.placeBlock((x+3,y+i,z+3),Block('dark_oak_log'))
        editor.placeBlock((x+3,y+i,z-3),Block('dark_oak_log'))
        editor.placeBlock((x-3,y+i,z+3),Block('dark_oak_log'))
        editor.placeBlock((x-3,y+i,z-3),Block('dark_oak_log'))
    for i in range(-2,3):
        editor.placeBlock((x+i,y+4,z+3),Block('dark_oak_log',{"axis": "x"}))
        editor.placeBlock((x+i,y+4,z-3),Block('dark_oak_log',{"axis": "x"}))
        editor.placeBlock((x+3,y+4,z+i),Block('dark_oak_log',{"axis": "z"}))
        editor.placeBlock((x-3,y+4,z+i),Block('dark_oak_log',{"axis": "z"}))
        editor.placeBlock((x+i,y+6,z+3),Block('dark_oak_log',{"axis": "x"}))
        editor.placeBlock((x+i,y+6,z-3),Block('dark_oak_log',{"axis": "x"}))
        editor.placeBlock((x+3,y+6,z+i),Block('dark_oak_log',{"axis": "z"}))
        editor.placeBlock((x-3,y+6,z+i),Block('dark_oak_log',{"axis": "z"}))
    for i in [-2,0,2]:
        editor.placeBlock((x+i,y+5,z+3),Block('spruce_stairs',{"facing": "north", "half": "top"}))
        editor.placeBlock((x+i,y+5,z-3),Block('spruce_stairs',{"facing": "south", "half": "top"}))
        editor.placeBlock((x+3,y+5,z+i),Block('spruce_stairs',{"facing": "west", "half": "top"}))
        editor.placeBlock((x-3,y+5,z+i),Block('spruce_stairs',{"facing": "east", "half": "top"}))
        editor.placeBlock((x+i,y+6,z+4),Block('stone_bricks'))
        editor.placeBlock((x+i,y+6,z-4),Block('stone_bricks'))
        editor.placeBlock((x+4,y+6,z+i),Block('stone_bricks'))
        editor.placeBlock((x-4,y+6,z+i),Block('stone_bricks'))
        editor.placeBlock((x+i,y+6,z+5),Block('stone_brick_slab'))
        editor.placeBlock((x+i,y+6,z-5),Block('stone_brick_slab'))
        editor.placeBlock((x+5,y+6,z+i),Block('stone_brick_slab'))
        editor.placeBlock((x-5,y+6,z+i),Block('stone_brick_slab'))
        editor.placeBlock((x+i,y+5,z+5),Block('stone_brick_slab',{"type": "top"}))
        editor.placeBlock((x+i,y+5,z-5),Block('stone_brick_slab',{"type": "top"}))
        editor.placeBlock((x+5,y+5,z+i),Block('stone_brick_slab',{"type": "top"}))
        editor.placeBlock((x-5,y+5,z+i),Block('stone_brick_slab',{"type": "top"}))
        editor.placeBlock((x+i,y+5,z+6),Block('stone_brick_slab',{"type": "top"}))
        editor.placeBlock((x+i,y+5,z-6),Block('stone_brick_slab',{"type": "top"}))
        editor.placeBlock((x+6,y+5,z+i),Block('stone_brick_slab',{"type": "top"}))
        editor.placeBlock((x-6,y+5,z+i),Block('stone_brick_slab',{"type": "top"}))
        editor.placeBlock((x+i,y+3,z+3),Block('oak_slab',{"type": "top"}))
        editor.placeBlock((x+i,y+3,z-3),Block('oak_slab',{"type": "top"}))
        editor.placeBlock((x+3,y+3,z+i),Block('oak_slab',{"type": "top"}))
        editor.placeBlock((x-3,y+3,z+i),Block('oak_slab',{"type": "top"}))
        editor.placeBlock((x+4,y+4,z+i),Block('oak_slab'))
        editor.placeBlock((x-4,y+4,z+i),Block('oak_slab'))
        editor.placeBlock((x+i,y+4,z+4),Block('oak_slab'))
        editor.placeBlock((x+i,y+4,z-4),Block('oak_slab'))
    for i in [-1,1]:
        editor.placeBlock((x+i,y+5,z+3),Block('oak_fence'))
        editor.placeBlock((x+i,y+5,z-3),Block('oak_fence'))
        editor.placeBlock((x+3,y+5,z+i),Block('oak_fence'))
        editor.placeBlock((x-3,y+5,z+i),Block('oak_fence'))
        editor.placeBlock((x+i,y+3,z+3),Block('oak_slab'))
        editor.placeBlock((x+i,y+3,z-3),Block('oak_slab'))
        editor.placeBlock((x+3,y+3,z+i),Block('oak_slab'))
        editor.placeBlock((x-3,y+3,z+i),Block('oak_slab'))
        editor.placeBlock((x+4,y+4,z+i),Block('oak_slab',{"type": "top"}))
        editor.placeBlock((x-4,y+4,z+i),Block('oak_slab',{"type": "top"}))
        editor.placeBlock((x+i,y+4,z+4),Block('oak_slab',{"type": "top"}))
        editor.placeBlock((x+i,y+4,z-4),Block('oak_slab',{"type": "top"}))
        if flag != 0:
            editor.placeBlock((x+i,y,z+3),Block('oak_slab',{"type": "top"}))
            editor.placeBlock((x+i,y,z-3),Block('oak_slab',{"type": "top"}))
            editor.placeBlock((x+3,y,z+i),Block('oak_slab',{"type": "top"}))
            editor.placeBlock((x-3,y,z+i),Block('oak_slab',{"type": "top"}))
    for i in [-3,-1,1,3]:
        editor.placeBlock((x+i,y+6,z+4),Block('stone_brick_slab'))
        editor.placeBlock((x+i,y+6,z-4),Block('stone_brick_slab'))
        editor.placeBlock((x+4,y+6,z+i),Block('stone_brick_slab'))
        editor.placeBlock((x-4,y+6,z+i),Block('stone_brick_slab'))
        editor.placeBlock((x+i,y+5,z+4),Block('stone_brick_slab',{"type": "top"}))
        editor.placeBlock((x+i,y+5,z-4),Block('stone_brick_slab',{"type": "top"}))
        editor.placeBlock((x+4,y+5,z+i),Block('stone_brick_slab',{"type": "top"}))
        editor.placeBlock((x-4,y+5,z+i),Block('stone_brick_slab',{"type": "top"}))
        editor.placeBlock((x+i,y+5,z+5),Block('stone_bricks'))
        editor.placeBlock((x+i,y+5,z-5),Block('stone_bricks'))
        editor.placeBlock((x+5,y+5,z+i),Block('stone_bricks'))
        editor.placeBlock((x-5,y+5,z+i),Block('stone_bricks'))
        editor.placeBlock((x+i,y+5,z+6),Block('stone_brick_slab'))
        editor.placeBlock((x+i,y+5,z-6),Block('stone_brick_slab'))
        editor.placeBlock((x+6,y+5,z+i),Block('stone_brick_slab'))
        editor.placeBlock((x-6,y+5,z+i),Block('stone_brick_slab'))
        editor.placeBlock((x+i,y+5,z+7),Block('smooth_stone_slab'))
        editor.placeBlock((x+i,y+5,z-7),Block('smooth_stone_slab'))
        editor.placeBlock((x+7,y+5,z+i),Block('smooth_stone_slab'))
        editor.placeBlock((x-7,y+5,z+i),Block('smooth_stone_slab'))
    editor.placeBlock((x+4,y+6,z+4),Block('stone_brick_slab',{"type": "top"}))
    editor.placeBlock((x+4,y+6,z-4),Block('stone_brick_slab',{"type": "top"}))
    editor.placeBlock((x-4,y+6,z+4),Block('stone_brick_slab',{"type": "top"}))
    editor.placeBlock((x-4,y+6,z-4),Block('stone_brick_slab',{"type": "top"}))
    editor.placeBlock((x+5,y+6,z+5),Block('stone_brick_slab',{"type": "top"}))
    editor.placeBlock((x+5,y+6,z-5),Block('stone_brick_slab',{"type": "top"}))
    editor.placeBlock((x-5,y+6,z+5),Block('stone_brick_slab',{"type": "top"}))
    editor.placeBlock((x-5,y+6,z-5),Block('stone_brick_slab',{"type": "top"}))
    editor.placeBlock((x+6,y+6,z+6),Block('stone_brick_slab',{"type": "top"}))
    editor.placeBlock((x+6,y+6,z-6),Block('stone_brick_slab',{"type": "top"}))
    editor.placeBlock((x-6,y+6,z+6),Block('stone_brick_slab',{"type": "top"}))
    editor.placeBlock((x-6,y+6,z-6),Block('stone_brick_slab',{"type": "top"}))
    editor.placeBlock((x+4,y+6,z+5),Block('stone_brick_slab'))
    editor.placeBlock((x+5,y+6,z+4),Block('stone_brick_slab'))
    editor.placeBlock((x+4,y+6,z-5),Block('stone_brick_slab'))
    editor.placeBlock((x+5,y+6,z-4),Block('stone_brick_slab'))
    editor.placeBlock((x-4,y+6,z+5),Block('stone_brick_slab'))
    editor.placeBlock((x-5,y+6,z+4),Block('stone_brick_slab'))
    editor.placeBlock((x-4,y+6,z-5),Block('stone_brick_slab'))
    editor.placeBlock((x-5,y+6,z-4),Block('stone_brick_slab'))
    editor.placeBlock((x+5,y+6,z+6),Block('stone_brick_slab'))
    editor.placeBlock((x+6,y+6,z+5),Block('stone_brick_slab'))
    editor.placeBlock((x+5,y+6,z-6),Block('stone_brick_slab'))
    editor.placeBlock((x+6,y+6,z-5),Block('stone_brick_slab'))
    editor.placeBlock((x-5,y+6,z+6),Block('stone_brick_slab'))
    editor.placeBlock((x-6,y+6,z+5),Block('stone_brick_slab'))
    editor.placeBlock((x-5,y+6,z-6),Block('stone_brick_slab'))
    editor.placeBlock((x-6,y+6,z-5),Block('stone_brick_slab'))
    editor.placeBlock((x+4,y+5,z+6),Block('stone_brick_slab',{"type": "top"}))
    editor.placeBlock((x+6,y+5,z+4),Block('stone_brick_slab',{"type": "top"}))
    editor.placeBlock((x+4,y+5,z-6),Block('stone_brick_slab',{"type": "top"}))
    editor.placeBlock((x+6,y+5,z-4),Block('stone_brick_slab',{"type": "top"}))
    editor.placeBlock((x-4,y+5,z+6),Block('stone_brick_slab',{"type": "top"}))
    editor.placeBlock((x-6,y+5,z+4),Block('stone_brick_slab',{"type": "top"}))
    editor.placeBlock((x-4,y+5,z-6),Block('stone_brick_slab',{"type": "top"}))
    editor.placeBlock((x-6,y+5,z-4),Block('stone_brick_slab',{"type": "top"}))
    for i in [-4,-2,0,2,4]:
        editor.placeBlock((x+i,y+5,z+7),Block('smooth_stone_slab',{"type": "top"}))
        editor.placeBlock((x+i,y+5,z-7),Block('smooth_stone_slab',{"type": "top"}))
        editor.placeBlock((x+7,y+5,z+i),Block('smooth_stone_slab',{"type": "top"}))
        editor.placeBlock((x-7,y+5,z+i),Block('smooth_stone_slab',{"type": "top"}))
    editor.placeBlock((x+5,y+6,z+7),Block('smooth_stone_slab'))
    editor.placeBlock((x+7,y+6,z+5),Block('smooth_stone_slab'))
    editor.placeBlock((x+5,y+6,z-7),Block('smooth_stone_slab'))
    editor.placeBlock((x+7,y+6,z-5),Block('smooth_stone_slab'))
    editor.placeBlock((x-5,y+6,z+7),Block('smooth_stone_slab'))
    editor.placeBlock((x-7,y+6,z+5),Block('smooth_stone_slab'))
    editor.placeBlock((x-5,y+6,z-7),Block('smooth_stone_slab'))
    editor.placeBlock((x-7,y+6,z-5),Block('smooth_stone_slab'))
    editor.placeBlock((x+6,y+6,z+7),Block('smooth_stone_slab',{"type": "top"}))
    editor.placeBlock((x+7,y+6,z+6),Block('smooth_stone_slab',{"type": "top"}))
    editor.placeBlock((x+6,y+6,z-7),Block('smooth_stone_slab',{"type": "top"}))
    editor.placeBlock((x+7,y+6,z-6),Block('smooth_stone_slab',{"type": "top"}))
    editor.placeBlock((x-6,y+6,z+7),Block('smooth_stone_slab',{"type": "top"}))
    editor.placeBlock((x-7,y+6,z+6),Block('smooth_stone_slab',{"type": "top"}))
    editor.placeBlock((x-6,y+6,z-7),Block('smooth_stone_slab',{"type": "top"}))
    editor.placeBlock((x-7,y+6,z-6),Block('smooth_stone_slab',{"type": "top"}))
    editor.placeBlock((x+7,y+7,z+7),Block('smooth_stone_slab'))
    editor.placeBlock((x+7,y+7,z-7),Block('smooth_stone_slab'))
    editor.placeBlock((x-7,y+7,z+7),Block('smooth_stone_slab'))
    editor.placeBlock((x-7,y+7,z-7),Block('smooth_stone_slab'))
    editor.placeBlock((x+7,y+6,z+7),Block('oak_fence'))
    editor.placeBlock((x+7,y+6,z-7),Block('oak_fence'))
    editor.placeBlock((x-7,y+6,z+7),Block('oak_fence'))
    editor.placeBlock((x-7,y+6,z-7),Block('oak_fence'))
    editor.placeBlock((x+7,y+5,z+7),Block('redstone_block'))
    editor.placeBlock((x+7,y+5,z-7),Block('redstone_block'))
    editor.placeBlock((x-7,y+5,z+7),Block('redstone_block'))
    editor.placeBlock((x-7,y+5,z-7),Block('redstone_block'))
    editor.placeBlock((x+7,y+4,z+7),Block('redstone_lamp',{"lit": "true"}))
    editor.placeBlock((x+7,y+4,z-7),Block('redstone_lamp',{"lit": "true"}))
    editor.placeBlock((x-7,y+4,z+7),Block('redstone_lamp',{"lit": "true"}))
    editor.placeBlock((x-7,y+4,z-7),Block('redstone_lamp',{"lit": "true"}))
    editor.placeBlock((x+7,y+3,z+7),Block('redstone_block'))
    editor.placeBlock((x+7,y+3,z-7),Block('redstone_block'))
    editor.placeBlock((x-7,y+3,z+7),Block('redstone_block'))
    editor.placeBlock((x-7,y+3,z-7),Block('redstone_block'))
    editor.placeBlock((x+8,y+4,z+7),Block('oak_trapdoor',{"facing": "east", "open": "true"}))
    editor.placeBlock((x+6,y+4,z+7),Block('oak_trapdoor',{"facing": "west", "open": "true"}))
    editor.placeBlock((x+7,y+4,z+8),Block('oak_trapdoor',{"facing": "south", "open": "true"}))
    editor.placeBlock((x+7,y+4,z+6),Block('oak_trapdoor',{"facing": "north", "open": "true"}))
    editor.placeBlock((x+8,y+4,z-7),Block('oak_trapdoor',{"facing": "east", "open": "true"}))
    editor.placeBlock((x+6,y+4,z-7),Block('oak_trapdoor',{"facing": "west", "open": "true"}))
    editor.placeBlock((x+7,y+4,z-6),Block('oak_trapdoor',{"facing": "south", "open": "true"}))
    editor.placeBlock((x+7,y+4,z-8),Block('oak_trapdoor',{"facing": "north", "open": "true"}))
    editor.placeBlock((x-6,y+4,z+7),Block('oak_trapdoor',{"facing": "east", "open": "true"}))
    editor.placeBlock((x-8,y+4,z+7),Block('oak_trapdoor',{"facing": "west", "open": "true"}))
    editor.placeBlock((x-7,y+4,z+8),Block('oak_trapdoor',{"facing": "south", "open": "true"}))
    editor.placeBlock((x-7,y+4,z+6),Block('oak_trapdoor',{"facing": "north", "open": "true"}))
    editor.placeBlock((x-6,y+4,z-7),Block('oak_trapdoor',{"facing": "east", "open": "true"}))
    editor.placeBlock((x-8,y+4,z-7),Block('oak_trapdoor',{"facing": "west", "open": "true"}))
    editor.placeBlock((x-7,y+4,z-6),Block('oak_trapdoor',{"facing": "south", "open": "true"}))
    editor.placeBlock((x-7,y+4,z-8),Block('oak_trapdoor',{"facing": "north", "open": "true"}))
    for i in range(-2,3):
        editor.placeBlock((x+i,y,z+2),Block('stone_bricks'))
        editor.placeBlock((x+i,y,z-2),Block('stone_bricks'))
        editor.placeBlock((x+2,y,z+i),Block('stone_bricks'))
        editor.placeBlock((x-2,y,z+i),Block('stone_bricks'))
        editor.placeBlock((x+i,y+1,z+2),Block('snow_block'))
        editor.placeBlock((x+i,y+1,z-2),Block('snow_block'))
        editor.placeBlock((x+2,y+1,z+i),Block('snow_block'))
        editor.placeBlock((x-2,y+1,z+i),Block('snow_block'))
        editor.placeBlock((x+i,y+2,z+2),Block('snow_block'))
        editor.placeBlock((x+i,y+2,z-2),Block('snow_block'))
        editor.placeBlock((x+2,y+2,z+i),Block('snow_block'))
        editor.placeBlock((x-2,y+2,z+i),Block('snow_block'))
        editor.placeBlock((x+i,y+3,z+2),Block('snow_block'))
        editor.placeBlock((x+i,y+3,z-2),Block('snow_block'))
        editor.placeBlock((x+2,y+3,z+i),Block('snow_block'))
        editor.placeBlock((x-2,y+3,z+i),Block('snow_block'))
    editor.placeBlock((x,y+1,z+2),Block('oak_fence'))
    editor.placeBlock((x,y+1,z-2),Block('oak_fence'))
    editor.placeBlock((x+2,y+1,z),Block('oak_fence'))
    editor.placeBlock((x-2,y+1,z),Block('oak_fence'))
    editor.placeBlock((x,y+2,z+2),Block('oak_fence'))
    editor.placeBlock((x,y+2,z-2),Block('oak_fence'))
    editor.placeBlock((x+2,y+2,z),Block('oak_fence'))
    editor.placeBlock((x-2,y+2,z),Block('oak_fence'))
    editor.placeBlock((x+3,y+2,z+2),Block('oak_stairs',{"facing": "south", "half": "top"}))
    editor.placeBlock((x+3,y+2,z-2),Block('oak_stairs',{"facing": "north", "half": "top"}))
    editor.placeBlock((x-3,y+2,z+2),Block('oak_stairs',{"facing": "south", "half": "top"}))
    editor.placeBlock((x-3,y+2,z-2),Block('oak_stairs',{"facing": "north", "half": "top"}))
    editor.placeBlock((x+2,y+2,z+3),Block('oak_stairs',{"facing": "east", "half": "top"}))
    editor.placeBlock((x-2,y+2,z+3),Block('oak_stairs',{"facing": "west", "half": "top"}))
    editor.placeBlock((x+2,y+2,z-3),Block('oak_stairs',{"facing": "east", "half": "top"}))
    editor.placeBlock((x-2,y+2,z-3),Block('oak_stairs',{"facing": "west", "half": "top"}))
    editor.placeBlock((x+4,y+3,z+3),Block('oak_stairs',{"facing": "west", "half": "top"}))
    editor.placeBlock((x+4,y+4,z+3),Block('oak_stairs',{"facing": "west", "half": "top"}))
    editor.placeBlock((x+5,y+4,z+3),Block('oak_stairs',{"facing": "west", "half": "top"}))
    editor.placeBlock((x+4,y+3,z-3),Block('oak_stairs',{"facing": "west", "half": "top"}))
    editor.placeBlock((x+4,y+4,z-3),Block('oak_stairs',{"facing": "west", "half": "top"}))
    editor.placeBlock((x+5,y+4,z-3),Block('oak_stairs',{"facing": "west", "half": "top"}))
    editor.placeBlock((x-4,y+3,z+3),Block('oak_stairs',{"facing": "east", "half": "top"}))
    editor.placeBlock((x-4,y+4,z+3),Block('oak_stairs',{"facing": "east", "half": "top"}))
    editor.placeBlock((x-5,y+4,z+3),Block('oak_stairs',{"facing": "east", "half": "top"}))
    editor.placeBlock((x-4,y+3,z-3),Block('oak_stairs',{"facing": "east", "half": "top"}))
    editor.placeBlock((x-4,y+4,z-3),Block('oak_stairs',{"facing": "east", "half": "top"}))
    editor.placeBlock((x-5,y+4,z-3),Block('oak_stairs',{"facing": "east", "half": "top"}))
    editor.placeBlock((x+3,y+3,z+4),Block('oak_stairs',{"facing": "north", "half": "top"}))
    editor.placeBlock((x+3,y+4,z+4),Block('oak_stairs',{"facing": "north", "half": "top"}))
    editor.placeBlock((x+3,y+4,z+5),Block('oak_stairs',{"facing": "north", "half": "top"}))
    editor.placeBlock((x-3,y+3,z+4),Block('oak_stairs',{"facing": "north", "half": "top"}))
    editor.placeBlock((x-3,y+4,z+4),Block('oak_stairs',{"facing": "north", "half": "top"}))
    editor.placeBlock((x-3,y+4,z+5),Block('oak_stairs',{"facing": "north", "half": "top"}))
    editor.placeBlock((x+3,y+3,z-4),Block('oak_stairs',{"facing": "south", "half": "top"}))
    editor.placeBlock((x+3,y+4,z-4),Block('oak_stairs',{"facing": "south", "half": "top"}))
    editor.placeBlock((x+3,y+4,z-5),Block('oak_stairs',{"facing": "south", "half": "top"}))
    editor.placeBlock((x-3,y+3,z-4),Block('oak_stairs',{"facing": "south", "half": "top"}))
    editor.placeBlock((x-3,y+4,z-4),Block('oak_stairs',{"facing": "south", "half": "top"}))
    editor.placeBlock((x-3,y+4,z-5),Block('oak_stairs',{"facing": "south", "half": "top"}))
    editor.placeBlock((x+4,y+5,z+4),Block('oak_slab'))
    editor.placeBlock((x+4,y+5,z-4),Block('oak_slab'))
    editor.placeBlock((x-4,y+5,z+4),Block('oak_slab'))
    editor.placeBlock((x-4,y+5,z-4),Block('oak_slab'))
    editor.placeBlock((x+4,y+5,z+5),Block('oak_slab',{"type": "top"}))
    editor.placeBlock((x+5,y+5,z+4),Block('oak_slab',{"type": "top"}))
    editor.placeBlock((x+5,y+5,z+5),Block('oak_slab',{"type": "top"}))
    editor.placeBlock((x+4,y+5,z-5),Block('oak_slab',{"type": "top"}))
    editor.placeBlock((x+5,y+5,z-4),Block('oak_slab',{"type": "top"}))
    editor.placeBlock((x+5,y+5,z-5),Block('oak_slab',{"type": "top"}))
    editor.placeBlock((x-4,y+5,z+5),Block('oak_slab',{"type": "top"}))
    editor.placeBlock((x-5,y+5,z+4),Block('oak_slab',{"type": "top"}))
    editor.placeBlock((x-5,y+5,z+5),Block('oak_slab',{"type": "top"}))
    editor.placeBlock((x-4,y+5,z-5),Block('oak_slab',{"type": "top"}))
    editor.placeBlock((x-5,y+5,z-4),Block('oak_slab',{"type": "top"}))
    editor.placeBlock((x-5,y+5,z-5),Block('oak_slab',{"type": "top"}))
    editor.placeBlock((x,y+5,z+2),Block('wall_torch',{"facing": "north"}))
    editor.placeBlock((x,y+5,z-2),Block('wall_torch',{"facing": "south"}))
    editor.placeBlock((x+2,y+5,z),Block('wall_torch',{"facing": "west"}))
    editor.placeBlock((x-2,y+5,z),Block('wall_torch',{"facing": "east"}))
    if flag != 0:
        editor.placeBlock((x+3,y,z),Block('oak_slab'))
        editor.placeBlock((x-3,y,z),Block('oak_slab'))
        editor.placeBlock((x,y,z+3),Block('oak_slab'))
        editor.placeBlock((x,y,z-3),Block('oak_slab'))
        editor.placeBlock((x+3,y+1,z+2),Block('oak_slab'))
        editor.placeBlock((x+3,y+1,z-2),Block('oak_slab'))
        editor.placeBlock((x-3,y+1,z+2),Block('oak_slab'))
        editor.placeBlock((x-3,y+1,z-2),Block('oak_slab'))
        editor.placeBlock((x+2,y+1,z+3),Block('oak_slab'))
        editor.placeBlock((x-2,y+1,z+3),Block('oak_slab'))
        editor.placeBlock((x+2,y+1,z-3),Block('oak_slab'))
        editor.placeBlock((x-2,y+1,z-3),Block('oak_slab'))
        editor.placeBlock((x+3,y,z+2),Block('oak_stairs',{"facing": "south"}))
        editor.placeBlock((x+3,y,z-2),Block('oak_stairs',{"facing": "north"}))
        editor.placeBlock((x-3,y,z+2),Block('oak_stairs',{"facing": "south"}))
        editor.placeBlock((x-3,y,z-2),Block('oak_stairs',{"facing": "north"}))
        editor.placeBlock((x+2,y,z+3),Block('oak_stairs',{"facing": "east"}))
        editor.placeBlock((x-2,y,z+3),Block('oak_stairs',{"facing": "west"}))
        editor.placeBlock((x+2,y,z-3),Block('oak_stairs',{"facing": "east"}))
        editor.placeBlock((x-2,y,z-3),Block('oak_stairs',{"facing": "west"}))
        editor.placeBlock((x+7,y-1,z),Block("lantern"))
        editor.placeBlock((x-7,y-1,z),Block("lantern"))
        editor.placeBlock((x,y-1,z+7),Block("lantern"))
        editor.placeBlock((x,y-1,z-7),Block("lantern"))
    if flag == 0:
        editor.placeBlock((x,y,z+2),Block('air'))
        editor.placeBlock((x,y,z-2),Block('air'))
        editor.placeBlock((x+2,y,z),Block('air'))
        editor.placeBlock((x-2,y,z),Block('air'))
        editor.placeBlock((x,y+1,z+2),Block('air'))
        editor.placeBlock((x,y+1,z-2),Block('air'))
        editor.placeBlock((x+2,y+1,z),Block('air'))
        editor.placeBlock((x-2,y+1,z),Block('air'))
    #light
    editor.placeBlock((x-5,y,z-5),Block("lantern"))
    editor.placeBlock((x-5,y,z+5),Block("lantern"))
    editor.placeBlock((x+5,y,z-5),Block("lantern"))
    editor.placeBlock((x+5,y,z+5),Block("lantern"))


def buildTowerTop(x, y, z):
    for i in range(-3,4):
        editor.placeBlock((x+i,y,z+3),Block('stone_bricks'))
        editor.placeBlock((x+i,y,z-3),Block('stone_bricks'))
        editor.placeBlock((x+3,y,z+i),Block('stone_bricks'))
        editor.placeBlock((x-3,y,z+i),Block('stone_bricks'))
    for i in range(-2,3):
        editor.placeBlock((x+i,y+1,z+2),Block('stone_bricks'))
        editor.placeBlock((x+i,y+1,z-2),Block('stone_bricks'))
        editor.placeBlock((x+2,y+1,z+i),Block('stone_bricks'))
        editor.placeBlock((x-2,y+1,z+i),Block('stone_bricks'))
    for i in range(-1,2):
        editor.placeBlock((x+i,y+2,z+1),Block('stone_bricks'))
        editor.placeBlock((x+i,y+2,z-1),Block('stone_bricks'))
        editor.placeBlock((x+1,y+2,z+i),Block('stone_bricks'))
        editor.placeBlock((x-1,y+2,z+i),Block('stone_bricks'))
    for i in [-2,0,2]:
        editor.placeBlock((x+i,y+1,z+3),Block('stone_brick_stairs',{"facing": "north"}))
        editor.placeBlock((x+i,y+1,z-3),Block('stone_brick_stairs',{"facing": "south"}))
        editor.placeBlock((x+3,y+1,z+i),Block('stone_brick_stairs',{"facing": "west"}))
        editor.placeBlock((x-3,y+1,z+i),Block('stone_brick_stairs',{"facing": "east"}))
    editor.placeBlock((x,y+2,z+2),Block('stone_brick_stairs',{"facing": "north"}))
    editor.placeBlock((x,y+2,z-2),Block('stone_brick_stairs',{"facing": "south"}))
    editor.placeBlock((x+2,y+2,z),Block('stone_brick_stairs',{"facing": "west"}))
    editor.placeBlock((x-2,y+2,z),Block('stone_brick_stairs',{"facing": "east"}))
    editor.placeBlock((x,y+3,z+1),Block('stone_brick_stairs',{"facing": "north"}))
    editor.placeBlock((x,y+3,z-1),Block('stone_brick_stairs',{"facing": "south"}))
    editor.placeBlock((x+1,y+3,z),Block('stone_brick_stairs',{"facing": "west"}))
    editor.placeBlock((x-1,y+3,z),Block('stone_brick_stairs',{"facing": "east"}))
    editor.placeBlock((x,y+3,z),Block('stone_brick_slab',{"type": "top"}))
    editor.placeBlock((x+7,y+1,z+7),Block('smooth_stone_slab',{"type": "double"}))
    editor.placeBlock((x-7,y+1,z+7),Block('smooth_stone_slab',{"type": "double"}))
    editor.placeBlock((x-7,y+1,z-7),Block('smooth_stone_slab',{"type": "double"}))
    editor.placeBlock((x+6,y,z+6),Block('smooth_stone_slab',{"type": "top"}))
    editor.placeBlock((x+6,y,z-6),Block('smooth_stone_slab',{"type": "top"}))
    editor.placeBlock((x-6,y,z+6),Block('smooth_stone_slab',{"type": "top"}))
    editor.placeBlock((x-6,y,z-6),Block('smooth_stone_slab',{"type": "top"}))
    editor.placeBlock((x+6,y+1,z+6),Block('smooth_stone_slab'))
    editor.placeBlock((x+6,y+1,z-6),Block('smooth_stone_slab'))
    editor.placeBlock((x-6,y+1,z+6),Block('smooth_stone_slab'))
    editor.placeBlock((x-6,y+1,z-6),Block('smooth_stone_slab'))
    editor.placeBlock((x+5,y+1,z+5),Block('smooth_stone_slab'))
    editor.placeBlock((x+5,y+1,z-5),Block('smooth_stone_slab'))
    editor.placeBlock((x-5,y+1,z+5),Block('smooth_stone_slab'))
    editor.placeBlock((x-5,y+1,z-5),Block('smooth_stone_slab'))
    editor.placeBlock((x+4,y+1,z+4),Block('smooth_stone_slab',{"type": "double"}))
    editor.placeBlock((x+4,y+1,z-4),Block('smooth_stone_slab',{"type": "double"}))
    editor.placeBlock((x-4,y+1,z+4),Block('smooth_stone_slab',{"type": "double"}))
    editor.placeBlock((x-4,y+1,z-4),Block('smooth_stone_slab',{"type": "double"}))
    editor.placeBlock((x+3,y+1,z+3),Block('smooth_stone_slab',{"type": "double"}))
    editor.placeBlock((x+3,y+1,z-3),Block('smooth_stone_slab',{"type": "double"}))
    editor.placeBlock((x-3,y+1,z+3),Block('smooth_stone_slab',{"type": "double"}))
    editor.placeBlock((x-3,y+1,z-3),Block('smooth_stone_slab',{"type": "double"}))
    editor.placeBlock((x+3,y+2,z+3),Block('smooth_stone_slab'))
    editor.placeBlock((x+3,y+2,z-3),Block('smooth_stone_slab'))
    editor.placeBlock((x-3,y+2,z+3),Block('smooth_stone_slab'))
    editor.placeBlock((x-3,y+2,z-3),Block('smooth_stone_slab'))
    editor.placeBlock((x+2,y+2,z+2),Block('smooth_stone_slab',{"type": "double"}))
    editor.placeBlock((x+2,y+2,z-2),Block('smooth_stone_slab',{"type": "double"}))
    editor.placeBlock((x-2,y+2,z+2),Block('smooth_stone_slab',{"type": "double"}))
    editor.placeBlock((x-2,y+2,z-2),Block('smooth_stone_slab',{"type": "double"}))
    editor.placeBlock((x+2,y+3,z+2),Block('smooth_stone_slab'))
    editor.placeBlock((x+2,y+3,z-2),Block('smooth_stone_slab'))
    editor.placeBlock((x-2,y+3,z+2),Block('smooth_stone_slab'))
    editor.placeBlock((x-2,y+3,z-2),Block('smooth_stone_slab'))
    editor.placeBlock((x+1,y+3,z+1),Block('smooth_stone_slab',{"type": "double"}))
    editor.placeBlock((x+1,y+3,z-1),Block('smooth_stone_slab',{"type": "double"}))
    editor.placeBlock((x-1,y+3,z+1),Block('smooth_stone_slab',{"type": "double"}))
    editor.placeBlock((x-1,y+3,z-1),Block('smooth_stone_slab',{"type": "double"}))
    editor.placeBlock((x+1,y+4,z+1),Block('smooth_stone_slab'))
    editor.placeBlock((x+1,y+4,z-1),Block('smooth_stone_slab'))
    editor.placeBlock((x-1,y+4,z+1),Block('smooth_stone_slab'))
    editor.placeBlock((x-1,y+4,z-1),Block('smooth_stone_slab'))
    editor.placeBlock((x,y+4,z),Block('smooth_stone_slab',{"type": "double"}))
    editor.placeBlock((x,y+5,z),Block('stone_bricks'))
    editor.placeBlock((x,y+6,z),Block('stone_bricks'))
    editor.placeBlock((x,y+5,z+1),Block('stone_brick_stairs',{"facing": "north", "half": "top"}))
    editor.placeBlock((x,y+5,z-1),Block('stone_brick_stairs',{"facing": "south", "half": "top"}))
    editor.placeBlock((x+1,y+5,z),Block('stone_brick_stairs',{"facing": "west", "half": "top"}))
    editor.placeBlock((x-1,y+5,z),Block('stone_brick_stairs',{"facing": "east", "half": "top"}))
    editor.placeBlock((x,y+6,z+1),Block('stone_brick_stairs',{"facing": "south"}))
    editor.placeBlock((x,y+6,z-1),Block('stone_brick_stairs',{"facing": "north"}))
    editor.placeBlock((x+1,y+6,z),Block('stone_brick_stairs',{"facing": "east"}))
    editor.placeBlock((x-1,y+6,z),Block('stone_brick_stairs',{"facing": "west"}))
    for i in range(6):
        editor.placeBlock((x,y+7+i,z),Block('stone_bricks'))
        editor.placeBlock((x,y+7+i,z+1),Block('smooth_stone_slab',{"type": "top"}))
        editor.placeBlock((x,y+7+i,z-1),Block('smooth_stone_slab',{"type": "top"}))
        editor.placeBlock((x+1,y+7+i,z),Block('smooth_stone_slab',{"type": "top"}))
        editor.placeBlock((x-1,y+7+i,z),Block('smooth_stone_slab',{"type": "top"}))
    for i in range(3):
        editor.placeBlock((x,y+13+i,z),Block('stone_bricks'))
    editor.placeBlock((x,y+13,z+1),Block('stone_brick_stairs',{"facing": "north", "half": "top"}))
    editor.placeBlock((x,y+13,z-1),Block('stone_brick_stairs',{"facing": "south", "half": "top"}))
    editor.placeBlock((x+1,y+13,z),Block('stone_brick_stairs',{"facing": "west", "half": "top"}))
    editor.placeBlock((x-1,y+13,z),Block('stone_brick_stairs',{"facing": "east", "half": "top"}))
    for i in range(3):
        editor.placeBlock((x,y+16+i,z),Block('cobblestone_wall'))
    editor.placeBlock((x,y+16,z+1),Block('cobblestone_wall'))
    editor.placeBlock((x,y+16,z-1),Block('cobblestone_wall'))
    editor.placeBlock((x+1,y+16,z),Block('cobblestone_wall'))
    editor.placeBlock((x-1,y+16,z),Block('cobblestone_wall'))
    editor.placeBlock((x,y+17,z+1),Block('torch'))
    editor.placeBlock((x,y+17,z-1),Block('torch'))
    editor.placeBlock((x+1,y+17,z),Block('torch'))
    editor.placeBlock((x-1,y+17,z),Block('torch'))
    editor.placeBlock((x,y+19,z),Block('torch'))
    #light
    editor.placeBlock((x+7,y,z),Block("lantern"))
    editor.placeBlock((x-7,y,z),Block("lantern"))
    editor.placeBlock((x,y,z+7),Block("lantern"))
    editor.placeBlock((x,y,z-7),Block("lantern"))
    editor.placeBlock((x+4,y+2,z+4),Block("lantern"))
    editor.placeBlock((x+4,y+2,z-4),Block("lantern"))
    editor.placeBlock((x-4,y+2,z+4),Block("lantern"))
    editor.placeBlock((x-4,y+2,z-4),Block("lantern"))
    editor.placeBlock((x,y+7,z),Block("shroomlight"))

def Bamboo(x,y,z,q_id,w_id,e_id):
    for yy in range(2):
        for xx in range(31):
            for zz in range(31):
                editor.placeBlock((x-15+xx,y-2+yy,z-15+zz),Block(q_id))
    def bamboo(x,y,z):
        for yy in range(random.randint(13,24)):
            editor.placeBlock((x,y+yy,z),Block(w_id))
    for i in range(50):
        bamboo(x-15+random.randint(0,7),y,z-15+random.randint(0,30))
        bamboo(x+15-random.randint(0,7),y,z-15+random.randint(0,30))
        bamboo(x-15+random.randint(0,30),y,z-15+random.randint(0,7))
        bamboo(x-15+random.randint(0,30),y,z+15-random.randint(0,7))
    def bamboo_sapling(x,y,z):
        p = editor.getBlock((x,y,z))
        if p is None:
            editor.placeBlock((x,y,z),Block(e_id))
    for i in range(15):
        bamboo_sapling(x-15+random.randint(0,7),y,z-15+random.randint(0,30))
        bamboo_sapling(x+15-random.randint(0,7),y,z-15+random.randint(0,30))
        bamboo_sapling(x-15+random.randint(0,30),y,z-15+random.randint(0,7))
        bamboo_sapling(x-15+random.randint(0,30),y,z+15-random.randint(0,7))
def Panda(x,y,z):
    def panda(x,y,z):
        p = editor.getBlock((x,y,z))
        if p is None:
            command = f"summon panda {x} {y} {z}"
            runCommand(command)
    for i in range(10):
        panda(x-15+random.randint(0,7),y,z-15+random.randint(0,30))
        panda(x+15-random.randint(0,7),y,z-15+random.randint(0,30))
        panda(x-15+random.randint(0,30),y,z-15+random.randint(0,7))
        panda(x-15+random.randint(0,30),y,z+15-random.randint(0,7))
    

def buildTower(x, y, z, level):
    buildTowerBottom(x, y, z)
    for i in range(level):
        buildTowerFloor(x, y+2+7*i, z, i)
    buildTowerTop(x, y+1+7*level, z)
    #Bamboo(x,y,z,"grass_block","bamboo","bamboo_sapling")
    Panda(x,y,z)



def rectanglesOverlap(r1, r2):
    """Check that r1 and r2 do not overlap."""
    if (r1 >= r2 + r2[2]) or (r1 + r1[2] <= r2) or (r1 + r1 <= r2) or (r1 >= r2 + r2):
        return False
    else:
        return True


